feature(global): #MEX-308 create global channels
OPEN-ENT-NG/rss pull request #1
Opened 2024-01-10 14:03 UTC by Mattox0

## Describe your changes

Add a CRUD for global channels and secure other endpoints about this globals channels.

## Checklist tests

- Create global channel from POSTMAN with Super Admin account
- GET, PUT and DELETE this channel
- Can see global channels in RSS widget
- Create a normal channel and edit them
- Edit a global channel

## Issue ticket number and link

**[https://jira.support-ent.fr/browse/MEX-308](https://jira.support-ent.fr/browse/MEX-308)**

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [X] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-01-15 10:56 UTC, qpic-cgi requested changes

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +            String id = request.params().get("id");
magic string

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +                final String id = request.params().get("id");
magic string

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +                final String id = request.params().get("id");
magic string

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +
oula ! n'utilise jamais ce format de construction de requête !
c'est comme ça qu'on créer des injections potentielles !
utilise ça plutôt: https://github.com/OPEN-ENT-NG/presences/blob/0f7072f208c09017ed84bf017d3bfbfc3600644d/common/src/main/java/fr/openent/presences/common/service/impl/DefaultUserService.java#L165

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +                    + " ON MATCH SET uac.rss= \"{\\\"no-display-rss-id\\\": %s}\"", userId, idString, idString);
Evite ce format ici aussi.
C'est quoi tout ces backslashs ? à mon avis tu peux rendre ça un peu plus propre

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +            String rss = result.right().getValue().getString(Field.PREFERENCES_RSS);
```suggestion
            handler.handle(new JsonObject(result.right().getValue().getString(Field.PREFERENCES_RSS, "{}")).getJsonArray(Field.PREFERENCES_NO_DISPLAY_ID, new JsonArray))
```

Ici, je t'ais transformé 9 lignes en 1 seule.

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/UtilsHelper.java
> +    }
ça me parait bien spécifique ton truc quand même ?
si ton channel actuel l'id de ton "channel" ou ton "globalArray" n'est pas dans ton tableau de "pref", alors tu l'ajoutes aux résultat ?

- cette méthodes me parait bien compliquée pour si peut, tu peux la rendre plus générique.
- utilise le "Stream" pour tes collections (tableau), et utilises les méthodes qu'il propose.
- modélise un maximum tes données.

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/UtilsHelper.java
> +    public static JsonArray mergeArray(JsonArray channels, JsonArray globalArray, JsonArray pref) {
attention, tu as l'air de faire du spécifique dans un helper (utils) qui est sensé être générique !
channels ? globalArray ? pref ? quelles sont ces choses ? connais pas !

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/UtilsHelper.java
> +    }
Pareil ici, ça m'a l'ai très spécifique !
Aussi (et toujours), utilises les streams, et modélise un maximum tes données.
stop les vilaines boucles imbriquées comme ça.

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/security/CustomOwner.java
> +            MongoAppFilter.executeCountQuery(request, this.conf.getCollection(), MongoQueryBuilder.build(query), 1, handler);
c'est quoi ce " 1 " ?

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +		}));
Ta méthode est bien lourde ! découpe moi ça en plusieurs méthodes pls.
Penses à modéliser tes données et utiliser des streams pour tes boucles.

2024-01-15 10:56 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +	}
découpage, stream et Models ;)

2024-01-15 15:34 UTC, qperie requested changes

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/constants/Field.java
> +    public static final String ID = "_id";
Appelle le plutôt _ID tant qu'à faire

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/security/CustomOwner.java
> +            QueryBuilder query = QueryBuilder.start("_id").is(id).or(QueryBuilder.start("owner.userId").is(user.getUserId()).get());
Magic strings

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/constants/Field.java
> +    public static final String ID = "_id";
Tu peux l'appeler _ID tant qu'à faire

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +		UserUtils.getUserInfos(eb, request, user -> channelService.list(user, arrayResponseHandler(request)));
Future -> UserUtils.getAuthenticatedUserInfos(eb, request)

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +            channelService.retrieve(id, user, notEmptyResponseHandler(request));
Future + magic string

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +            }
Future + magic string + indentation + log error

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +        });
Future + magic string + indentation

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +    public static void getPreferences(String userId, Handler<Either<String, JsonArray>> handler) {
Future

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +    public static void addPreferences(String userId, JsonArray globalArray, Handler<Either<String, JsonArray>> handler) {
Future

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +            }
stream

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +                handler.handle(new Either.Left<>(result.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/helpers/PreferenceHelper.java
> +                handler.handle(new Either.Left<>(resultPreferences.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelGlobalService.java
> +    public void deleteGlobalChannel(String idChannel, Handler<Either<String, JsonObject>> handler);
Futures + java doc

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelGlobalServiceMongoImpl.java
> +    public void createGlobalChannel(UserInfos user, JsonObject channel, Handler<Either<String, JsonObject>> handler) {
Future

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelGlobalServiceMongoImpl.java
> +    public void list(Handler<Either<String, JsonArray>> arrayResponseHandler) {
Future

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelGlobalServiceMongoImpl.java
> +    public void deleteGlobalChannel(String idChannel, Handler<Either<String, JsonObject>> handler) {
Future

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
> +            } else {
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssGlobalController.java
> +        });
Future + log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssGlobalController.java
> +        });
Future + log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssGlobalController.java
> +        });
Future + magic string +log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
>  	@SecuredAction(value = "channel.create", type = ActionType.AUTHENTICATED)
Droit workflow ou AUTHENTICATED ? (l'un des deux est faux ou sert à rien)

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
>  	@SecuredAction(value = "channel.list", type = ActionType.AUTHENTICATED)
Droit workflow ou AUTHENTICATED ? (l'un des deux est faux ou sert à rien)

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
>  	@SecuredAction(value = "channel.read", type = ActionType.RESOURCE)
Précise le @ResourceFilter si possible
Et vu qu'il n'y a pas de système de partage le "channel.read" est probablement inutile

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
>  	@SecuredAction(value = "", type = ActionType.RESOURCE)
Précise le @ResourceFilter si possible

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
>  	@SecuredAction(value = "", type = ActionType.RESOURCE)
Précise le @ResourceFilter si possible

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/controller/RssController.java
>  	@SecuredAction(value = "feed.read", type = ActionType.AUTHENTICATED)
Droit workflow ou AUTHENTICATED ? (l'un des deux est faux ou sert à rien)

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/helpers/UtilsHelper.java
> +public class UtilsHelper {
Globalement tu peux faire des stream pour simplifier un peu toutes les boucles de tes utilitaires

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +	public void create(UserInfos user, JsonObject channel, Handler<Either<String, JsonObject>> handler) {
Future

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
>  	public void list(UserInfos user, Handler<Either<String, JsonArray>> arrayResponseHandler) {
Future si ça implique pas trop de changement là où elle était potentiellement déjà appelée

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +	public void update(String userId, String idChannel, JsonArray feeds, Handler<Either<String, JsonObject>> handler) {
Future

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
>  public class ChannelServiceMongoImpl extends MongoDbCrudService implements ChannelService {
Pense à modifier l'interface ChannelService aussi !

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +	public void deleteChannel(String userId, String idChannel, Handler<Either<String, JsonObject>> handler) {
Future si ça implique pas trop de changement là où elle était potentiellement déjà appelée

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +				handler.handle(new Either.Left<>(result.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +				arrayResponseHandler.handle(new Either.Left<>(result.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +					arrayResponseHandler.handle(new Either.Left<>(resultPref.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +						arrayResponseHandler.handle(new Either.Left<>(globalList.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +				handler.handle(new Either.Left<>(result.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +						handler.handle(new Either.Left<>(globalList.left().getValue()));
log

2024-01-15 15:34 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +							handler.handle(new Either.Left<>(resultPreferences.left().getValue()));
log

2024-01-24 11:57 UTC, qperie requested changes

2024-01-24 11:57 UTC, qperie commented on src/main/java/net/atos/entng/rss/model/Channel.java
> +    }
Sur tes set, return this plutôt, ça permet d'en chainer plusieurs si on veut définir des valeurs comme ça

```suggestion
    public Channel setId(String id) {
        this._id = id;
        return this;
    }
```

2024-01-24 11:57 UTC, qperie commented on src/main/java/net/atos/entng/rss/model/Channel.java
> +            .put(Field.FEEDS, this.feeds);
Tu peux simplifier en utilisant le IModelHelper :
```suggestion
        return IModelHelper.toJson(Channel.class, false, false);
```

2024-01-24 11:57 UTC, qperie commented on src/main/java/net/atos/entng/rss/model/ChannelFeed.java
> +    }
unused

2024-01-24 11:57 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelGlobalServiceMongoImpl.java
> +    public Future<JsonObject> createGlobalChannel(UserInfos user, JsonObject feeds) {
feed plutôt que feeds vu que y'en a qu'un.
Et bien penser à modifier l'interface aussi.
Et pareil pour Channel

2024-01-24 11:57 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelGlobalServiceMongoImpl.java
> +                    .collect(ArrayList::new, List::add, List::addAll);
```suggestion
                   .collect(Collectors.toList());
```
Si tu veux simplifier

2024-01-24 11:57 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +				});
Logique qui devrait être dans le controller et non pas ici. Le service devrait te renvoyer tes channels perso puis dans ton controller tu compose en récupérant les globaux et tu les merge ensemble

2024-01-24 11:57 UTC, qperie commented on src/main/java/net/atos/entng/rss/service/ChannelServiceMongoImpl.java
> +						log.error("[RSS@ChannelServiceMongo::update] Can't get channels");
```suggestion
						log.error("[RSS@ChannelServiceMongoImpl::update] Can't get channels");
```
Un peu partout dans le fichier

2024-02-05 09:46 UTC, qpic-cgi requested changes

2024-02-05 09:46 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/IModelHelper.java
> +                }
```suggestion
                if (object == null && !ignoreNull)
```

2024-02-05 09:46 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/IModelHelper.java
> +                if (errorMessage != null) {
Ici, même si tu n'as n'as pas de message, il faut que tu log quelque chose, afin qu'on soit systématiquement au courant que quelque chose a planté.

2024-02-05 09:46 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/helpers/IModelHelper.java
> +                    log.error(errorMessage + " " + event.left().getValue());
CF commentaire du dessus

2024-02-05 09:46 UTC, qpic-cgi commented on src/main/java/net/atos/entng/rss/service/ChannelGlobalServiceMongoImpl.java
> +                promise.fail(results.left().getValue());
logs ?

2024-02-05 10:07 UTC, qpic-cgi approved these changes

2024-02-05 10:43 UTC, qperie approved these changes

2024-02-05 10:50 UTC, merged